version: "3.1"
services:

    api_mariadb:
      image: mariadb:latest
      container_name: api_mariadb
      restart: unless-stopped
      tty: true
      volumes:
       - ./bd/mariadb:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=root-pass
        - MYSQL_DATABASE=api
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
        - TZ=America/Sao_Paulo
        
      ports:
        - "3306:3306"
      networks:
        - api

    api_nginx:
      image: nginx:alpine
      container_name: api_nginx
      restart: unless-stopped
      tty: true
      working_dir: /application
      volumes:
        - ./backend/src:/application
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
      links:
        - api_mariadb
      networks:
        - api

    api_php:
      build: backend
      container_name: api_php
      restart: unless-stopped
      tty: true
      working_dir: /application
      volumes:
        - ./backend/src:/application
      networks:
        - api

networks:
  api:
    driver: bridge

volumes:
  database:
    driver: local